In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('campus_placement_data (1).csv')

In [3]:
df.head()

,student_id,gender,age,city_tier,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_stream,degree_percentage,...,technical_skills_score,soft_skills_score,aptitude_score,communication_score,work_experience_months,leadership_roles,extracurricular_activities,backlogs,placed,salary_lpa
0,STU000001,Male,22,Tier 1,71.01,State,76.76,CBSE,Commerce,64.44,...,6.8,7.8,62.1,6.2,14,1,10,0,1,12.24
1,STU000002,Female,22,Tier 2,58.46,CBSE,57.62,State,Science,68.24,...,4.6,4.8,58.7,7.2,5,1,4,0,1,10.09
2,STU000003,Female,21,Tier 1,67.83,CBSE,65.67,State,Commerce,52.33,...,4.7,5.0,58.9,5.0,30,2,1,0,1,14.94
3,STU000004,Female,21,Tier 2,80.40,CBSE,77.15,State,Science,56.55,...,6.8,7.6,35.0,8.3,31,0,5,0,1,15.49
4,STU000005,Male,21,Tier 1,66.10,State,62.81,ICSE,Science,78.93,...,7.0,5.7,54.0,5.4,24,0,2,0,1,15.13

In [4]:
df.columns

Index(['student_id', 'gender', 'age', 'city_tier', 'ssc_percentage',
       'ssc_board', 'hsc_percentage', 'hsc_board', 'hsc_stream',
       'degree_percentage', 'degree_field', 'mba_percentage', 'specialization',
       'internships_count', 'projects_count', 'certifications_count',
       'technical_skills_score', 'soft_skills_score', 'aptitude_score',
       'communication_score', 'work_experience_months', 'leadership_roles',
       'extracurricular_activities', 'backlogs', 'placed', 'salary_lpa'],
      dtype='object')

In [5]:
df = df.drop(['student_id','hsc_board','hsc_stream','mba_percentage','specialization','certifications_count','technical_skills_score','soft_skills_score','aptitude_score','work_experience_months','leadership_roles','extracurricular_activities','salary_lpa'],axis = 1)

In [11]:
df.columns

Index(['gender', 'age', 'city_tier', 'ssc_percentage', 'ssc_board',
       'hsc_percentage', 'degree_percentage', 'degree_field',
       'internships_count', 'projects_count', 'communication_score',
       'backlogs', 'placed'],
      dtype='object')

In [13]:
df = df.drop(['ssc_board'], axis = 1)

In [15]:
df.columns

Index(['gender', 'age', 'city_tier', 'ssc_percentage', 'hsc_percentage',
       'degree_percentage', 'degree_field', 'internships_count',
       'projects_count', 'communication_score', 'backlogs', 'placed'],
      dtype='object')

In [17]:
df.head()

,gender,age,city_tier,ssc_percentage,hsc_percentage,degree_percentage,degree_field,internships_count,projects_count,communication_score,backlogs,placed
0,Male,22,Tier 1,71.01,76.76,64.44,Engineering,1,2,6.2,0,1
1,Female,22,Tier 2,58.46,57.62,68.24,Business,1,1,7.2,0,1
2,Female,21,Tier 1,67.83,65.67,52.33,Engineering,4,3,5.0,0,1
3,Female,21,Tier 2,80.40,77.15,56.55,Engineering,2,3,8.3,0,1
4,Male,21,Tier 1,66.10,62.81,78.93,Engineering,1,4,5.4,0,1

In [19]:
df = df.replace(['Male' , 'Female' , 'Other'] , [0,1,2])

C:\Users\YASH\AppData\Local\Temp\ipykernel_27680\2722227697.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(['Male' , 'Female' , 'Other'] , [0,1,2])

In [21]:
df.head()

,gender,age,city_tier,ssc_percentage,hsc_percentage,degree_percentage,degree_field,internships_count,projects_count,communication_score,backlogs,placed
0,0,22,Tier 1,71.01,76.76,64.44,Engineering,1,2,6.2,0,1
1,1,22,Tier 2,58.46,57.62,68.24,Business,1,1,7.2,0,1
2,1,21,Tier 1,67.83,65.67,52.33,Engineering,4,3,5.0,0,1
3,1,21,Tier 2,80.40,77.15,56.55,Engineering,2,3,8.3,0,1
4,0,21,Tier 1,66.10,62.81,78.93,Engineering,1,4,5.4,0,1

In [23]:
df.tail()

,gender,age,city_tier,ssc_percentage,hsc_percentage,degree_percentage,degree_field,internships_count,projects_count,communication_score,backlogs,placed
99995,1,22,Tier 1,70.03,58.73,48.01,Business,2,4,10.0,5,1
99996,1,22,Tier 2,81.48,65.48,45.00,Engineering,5,4,9.2,0,1
99997,1,20,Tier 2,79.29,70.13,75.24,Engineering,2,2,7.1,1,1
99998,0,22,Tier 1,74.81,74.79,92.22,Arts,1,6,8.3,0,1
99999,0,18,Tier 3,67.20,66.32,67.83,Engineering,0,2,8.5,1,1

In [25]:
df['degree_field'].unique()

array(['Engineering', 'Business', 2, 'Arts', 'Science'], dtype=object)

In [27]:
df['degree_field'].isnull().sum()

0

In [29]:
 df = df[~df['degree_field'].isin([2 ,'2'])]

In [31]:
df['degree_field'].unique()

array(['Engineering', 'Business', 'Arts', 'Science'], dtype=object)

In [33]:
df.head()

,gender,age,city_tier,ssc_percentage,hsc_percentage,degree_percentage,degree_field,internships_count,projects_count,communication_score,backlogs,placed
0,0,22,Tier 1,71.01,76.76,64.44,Engineering,1,2,6.2,0,1
1,1,22,Tier 2,58.46,57.62,68.24,Business,1,1,7.2,0,1
2,1,21,Tier 1,67.83,65.67,52.33,Engineering,4,3,5.0,0,1
3,1,21,Tier 2,80.40,77.15,56.55,Engineering,2,3,8.3,0,1
4,0,21,Tier 1,66.10,62.81,78.93,Engineering,1,4,5.4,0,1

In [35]:
df.isnull().sum()

gender                 0
age                    0
city_tier              0
ssc_percentage         0
hsc_percentage         0
degree_percentage      0
degree_field           0
internships_count      0
projects_count         0
communication_score    0
backlogs               0
placed                 0
dtype: int64

In [44]:
x = df.drop(['placed'],axis = 1)
y = df['placed']

In [46]:
x = x.rename(columns = {'ssc_percentage' : 'tenth_percentage' , 'hsc_percentage' : 'twelfth_percentage'})

In [48]:
x.columns

Index(['gender', 'age', 'city_tier', 'tenth_percentage', 'twelfth_percentage',
       'degree_percentage', 'degree_field', 'internships_count',
       'projects_count', 'communication_score', 'backlogs'],
      dtype='object')

In [50]:
df['degree_field'].unique()

array(['Engineering', 'Business', 'Arts', 'Science'], dtype=object)

In [52]:
 x = x.drop(['backlogs'] , axis = 1)

In [54]:
 x = x.drop(['communication_score'] , axis = 1)

In [56]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y ,test_size = 0.2  , random_state = 42)

In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [60]:
categorical_cols = [
    'city_tier',
    'degree_field'
]

In [62]:
preprocessor = ColumnTransformer(transformers=[('cat',OneHotEncoder(handle_unknown='ignore'),categorical_cols)],remainder='passthrough')

In [64]:
pipe = Pipeline([('preprocessor', preprocessor),('model', LogisticRegression())])

In [66]:
pipe.fit(x_train , y_train)

C:\Users\YASH\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\YASH\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['city_tier',
                                                   'degree_field'])])),
                ('model', LogisticRegression())])

In [68]:
y_pred = pipe.predict(x_test)

In [70]:
pipe.score(x_test , y_test)

0.8448055200044516

In [76]:
import joblib

joblib.dump(pipe, "placement_predictor.pkl")

['placement_predictor.pkl']

In [74]:
print(df['gender'].unique())
print(df['city_tier'].unique())
print(df['degree_field'].unique())

[0 1 2]
['Tier 1' 'Tier 2' 'Tier 3']
['Engineering' 'Business' 'Arts' 'Science']

In [78]:
sample = pd.DataFrame({
    'gender':[0],
    'age':[22],
    'tenth_percentage':[85],
    'twelfth_percentage':[78],
    'degree_percentage':[80],
    'internships_count':[2],
    'projects_count':[4],
    'city_tier':['Tier 2'],
    'degree_field':['Engineering']
})

print(pipe.predict(sample))

[1]